### PR TITLE
Olof hound

### PR DESCRIPTION
**Pull request by olofenglund96**

### CODE REVIEW

**Comment by navro** [comment]
@olofenglund96 Will this be mergeable tomorrow? :champagne:

**Comment by olofenglund96** [comment]
@navro Working on it! I won't fix all the errors hounds are giving. Instead I suggest we do it over time when we feel like. It's too much work to finish until tomorrow without generating loads of bugs.

**Comment by FredrikLastow** [comment]
Maybe we should make another readme commit then tomorrow and merge that instead?

**Comment by olofenglund96** [comment]
@navro @FredrikLastow I think this is done now. I should probably not be the one changing the files anyways since I didn't write them and I am not as familiar with how the code works etc. The purpose of this PR is only to add hound, not change all the files he complains about.

**Comment by FredrikLastow** [comment]
Sounds good! Woof away my friend

**Pull request merged**
