### PR TITLE
General bug fixes

### LINKED ISSUE #45: Messages (Android)
Message-name doesn't always show on android while in a chat

### PR DESCRIPTION
**Pull request by FredrikLastow**
- Closes #45 
- Fixes long group names not being displayed properly on both ios and android
- Fixes navbar with back link on all pages (the ones you go to from the first page of tabs e.g. event) on android.
- Fixes messages navbar with groupname on android.
- Made tab icons white on active in android aswell
- Removed unnecessary hideShowTabbar() function in index.js

### CODE REVIEW

**Comment by olofenglund96** [comment]
I think we should have backbuttons for android. I get confused when the navbar totally dissapear (as when viewing events). My personal preference is of course not as convincing as the fact that almost all applications with a navbar has a backbutton (I checked Facebook, Instagram, Snapchat, Gmail, Google Calendar, Android store among others). I say we follow the established design patterns.

**Comment by FredrikLastow** [comment]
I agree. I always felt like something was missing on those pages - they were a bit empty. I thought this solution was better than manually displaying the navbar on every page we want it, because we want it on every page execept intex.html. Better to remove it manually than add it manually if we almost always want it. This also adds it for all future pages aswell. If you don't want it on any page you can now just add the no-navbar class to the page instead of using js.

**Comment by navro** [comment]
I can accept a discrete, arrow back button on android (no text). The current version takes up too much space and the important center part will be shortened if the total length is too long

**Comment by FredrikLastow** [comment]
That's true. Good point. I will fix that

**Comment by navro** [comment]
As for the navbar, it needs to be placed on each page. This PR makes it look like the different pages are placed below index, since the tabbar goes up and displays the navbar underneath it. With the old code the entire page was loaded in a single animation, which looked much better

**Comment by FredrikLastow** [comment]
https://gyazo.com/4e39a6a4103a50beff652d8685a675c2

**Comment by FredrikLastow** [comment]
Okay, I will see if I can fix that too

**Pull request merged**
