### PR TITLE
Message improvements

### PR DESCRIPTION
**Pull request by navro**
* Adds a real `send` button. No need to press enter anymore :D
* Allow multi line messages
* Messages can now be copied
* Clean up of `messages.js`
* Fixed some eslint errors/warnings

iOS testers wanted! Please check that the `send` button works properly
(keyboard should stay up)

### CODE REVIEW

**Comment by FredrikLastow** [comment]
A send button!? What a guy! You're spoiling the whole section Jakob :D

**Comment by navro** [comment]
> A send button!? What a guy! You're spoiling the whole section Jakob :D

Haha :joy: 
I finally found a way to keep the keyboard from going down and then up again when the button was pressed. At least on android :cold_sweat:

**Comment by navro** [comment]
Tested and working in iOS :heavy_check_mark:

**Comment by navro** [comment]
Next project: image upload
I have already written the backend part :smile:

**Comment by FredrikLastow** [comment]
The god. He never cease to impress me

**Comment by navro** [comment]
> The god

No, that's @davidwessman :wink:

**Comment by davidwessman** [comment]
> The god
> No, that's @davidwessman 😉

^^

**Pull request merged**
